---
title: "Can British homeworkers have more stable work schedules? A time-use approach to measure work schedule instability"
author: "Zhuofei Lu and Laurent Lesnard"
format: docx
editor: visual
bibliography: references.bib
---

## 1. Introduction

A growing body of literature recognises that 'work schedule instability' can lead to worse well-being status and a series of mental issues, including irregular health practises, mental distress, poor sleep quality, and unhappiness [@schneider2019; @ananat2020]. Although there is a rich research tradition investigating the consequences of work schedule instability for worker health and well-being [@carrillo2017; @harknett2020; @luhr2022], far too little attention has been paid to the predictors of work schedule instability. In addition, the definitions and measurements of work schedule instability in current literature are almost all based on respondents' irregular work arrangments controlled by employers (i.e., cancelled shifts or any schedule change experience) [@carrillo2017; @harknett2020] or working time patterns based on long-term memories (i.e., week-to-week hours variation in the past month) [@schneider2019] but not 24-hour daily time use data. The studies that use these 'work-domain-oriented' measurements tend to assume 'work schedule instability' are mainly caused by factors in the work domain but ignore the fact that workers also can control their work schedule to facilitate private/family demands, thereby increasing their work schedule instability [@chung2022; @cornwell2013]. In particular, during the last decades, flexible working arrangements have become common rights in the UK labour market, which allow workers to decide when and where to work flexibly [@lu2023]. Such changes led to numerous debates and studies aimed especially at predicting the impacts of working from home on time use patterns and time quality indexes related to work-life balance [@offer2011; @craig2016]. Therefore, it is necessary to find out an objective measure of work schedule instability based on workers' accurate time use data.

      In this study, we expect that working from home can shape workers' work schedule instability by offering more work autonomy and flexibility, while such associations still subject to ongoing debates due to the lack of empirical evidence. On the one hand, according to the resource (drain) perspective in the work‐family spillover theory [@greenhaus1985; @frone1992], some scholars predict that workers tend to have more time and energy to manage their work schedule when working from home since they might have more work autonomy and flexibility to address work-family conflicts [@lu2023a; @li2022]. On the other hand, some sociologists of work are worrying about the potential adverse effects of working from home and emphasise the potential role-blurring effects [@yucel2021; @wheatley2012]. This is because workers might increase work schedule instability when working from home due to the blurring of the temporal and spatial boundaries between their work commitments and private life [@zerubavel1979; @clark2000]. Overall, there are conflicting theoretical predictions about the associations between working from home and work schedule instability. Owing to the limitation of time use data and methods used, no direct dialogue is available. Therefore, the study's first objective is to explore how working from home shape workers' work schedule instability by using 24-hour time use data to measure work schedule instability.

       Moreover, given that workers' experience in the labour market and time use patterns are highly gendered and class-differentiated, we expect that the associations between working from home and work schedule instability might vary across gender, occupational class and the combination of the two. For men, workers in the higher (i.e., professional and managerial classes) groups and the lower (i.e., routine and manual classes) groups share different bargaining power and job demands and security, making them suffer different risks in terms of work schedule instability [@dumont2012; @warren2015; @bianchi2014]. For example, the higher occupational groups might exchange the right to work at home with their high bargaining power [@dumont2012], while the lower groups might passively work at home since they do not have other choices [@bathini2017]. As for women, other than class disparities in the labour market, female workers in different occupational classes suffer from different stress-related exposures and different degrees of worse time quality (i.e., time fragmentation and contaminated free time) in their households [@carrillo2017a; @craig2016], making them at different risk when working from home and dealing with work schedule instability. For instance, women in the lower occupational groups might share more household responsibilities and have fewer resources (i.e., money, time and energy) to manage work schedules [@hu2017; @syrda2022].

       By achieving both objectives, this study tends to make two important contributions to the literature. First, we empirically extend the previous research by developing an objective measure of work schedule instability by using workers' 24-hour time use data. Specifically, in the UK time use survey 2020-2021, respondents were asked to record every single working episode (10 minutes/1 episode) within 24 hours. Thus, we are able to identify 'hamming distance' to measure similarities between sequences [@lesnard2010]. (Here we need more introduction about hamming distance). See Table \[X\] for more details about the measurement of hamming distance. Second, the study provides novel insights into the debate about whether and how working from home shapes workers' work schedule instability across gender and occupational class.

## 2. Literature review

## 3. Analysis

The sample of this study is drawn from the Centre for Time Use Research (CTUR) UK Time Use Survey across the COVID-19 pandemic. The dataset is a population-representative (quota sample) time-use diary data collected by the Centre for Time Use Research through an online Click and Drag Diary Instrument (CaDDI). Representative quotas were established for the gender, age group, region, and social class distribution of the population. As part of the survey, respondents were given online time-use diaries, and were asked to record what they were doing, how they were doing it, and their feelings towards their activities during 144 10-minute episodes across the day [@sullivan2021]. In addition to the diaries, the dataset contains information about standard socio-demographic variables and mental health. Respondents completed the online time-use diaries for between 1 and 3 days, yielding diary data for around 5800 diary days across 2020-2021. The sample first excluded those who were not in paid employment. Then, we selected those who reported at least two work diary days as the target sample (X%). After excluding the samples with missing data (around X%) or extreme values such as 0 or 24 working hours per day (around X%), The final analytic sample came to include X adult workers who have at least two 24-hour working day diaries. More details about the sample can be seen in Table X.
